"""add is_cancelled and completed_at to tasks

Revision ID: 2a3010bdf826
Revises: f1004e8202e1
Create Date: 2026-07-13 22:18:05.495977

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a3010bdf826"
down_revision: Union[str, Sequence[str], None] = "f1004e8202e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_client_team_member"), "client_team_members", type_="unique"
    )
    op.add_column(
        "tasks",
        sa.Column("is_cancelled", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "tasks", sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "completed_at")
    op.drop_column("tasks", "is_cancelled")
    op.create_unique_constraint(
        op.f("uq_client_team_member"),
        "client_team_members",
        ["client_id", "user_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
