"""add due_day and due_days_from_start to templates, priority and nullable due_day to activities

Revision ID: 359ccfa717d1
Revises: da980b2122bb
Create Date: 2026-06-02 09:55:15.741543

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "359ccfa717d1"
down_revision: Union[str, Sequence[str], None] = "da980b2122bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity_templates", sa.Column("due_day", sa.Integer(), nullable=True)
    )
    op.add_column(
        "activity_templates",
        sa.Column("due_days_from_start", sa.Integer(), nullable=True),
    )
    op.add_column(
        "template_activities",
        sa.Column(
            "priority", sa.String(length=20), server_default="medium", nullable=False
        ),
    )
    op.alter_column(
        "template_activities", "due_day", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "template_activities", "due_day", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("template_activities", "priority")
    op.drop_column("activity_templates", "due_days_from_start")
    op.drop_column("activity_templates", "due_day")
    # ### end Alembic commands ###
