"""Add deleted_at to clients

Revision ID: 3b813df4ed3f
Revises: 03b662a6a1bb
Create Date: 2026-04-16 18:05:20.507997

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b813df4ed3f"
down_revision: str | Sequence[str] | None = "03b662a6a1bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "deleted_at")
    # ### end Alembic commands ###
