"""add routine_instance_id to tasks

Revision ID: 42cfed5605d5
Revises: 2a3010bdf826
Create Date: 2026-07-17 08:45:56.363806

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42cfed5605d5"
down_revision: Union[str, Sequence[str], None] = "2a3010bdf826"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("routine_instance_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_tasks_routine_instance_id"),
        "tasks",
        ["routine_instance_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_routine_instance_id"), table_name="tasks")
    op.drop_column("tasks", "routine_instance_id")
    # ### end Alembic commands ###
