"""add project applications and conversion nullable

Revision ID: 6befb539f062
Revises: 1150e26f850e
Create Date: 2026-09-09 02:44:29.337915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6befb539f062'
down_revision: Union[str, Sequence[str], None] = '1150e26f850e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'applicant_id', name='uq_project_applications_project_applicant')
    )
    op.create_index(op.f('ix_project_applications_applicant_id'), 'project_applications', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_project_applications_project_id'), 'project_applications', ['project_id'], unique=False)
    op.add_column('conversations', sa.Column('application_id', sa.UUID(), nullable=True))
    op.alter_column('conversations', 'invitation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_conversations_application_id'), 'conversations', ['application_id'], unique=True)
    op.create_foreign_key(None, 'conversations', 'project_applications', ['application_id'], ['id'])
    op.add_column('projects', sa.Column('applications_closed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'applications_closed')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_application_id'), table_name='conversations')
    op.alter_column('conversations', 'invitation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('conversations', 'application_id')
    op.drop_index(op.f('ix_project_applications_project_id'), table_name='project_applications')
    op.drop_index(op.f('ix_project_applications_applicant_id'), table_name='project_applications')
    op.drop_table('project_applications')
    # ### end Alembic commands ###
