"""add_name_company_to_users

Revision ID: 7ed13e88c8f0
Revises: 345fdaac3155
Create Date: 2026-04-11 01:34:44.610040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed13e88c8f0'
down_revision: Union[str, Sequence[str], None] = '345fdaac3155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('company', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'company')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
