"""add is_active to discussion posts and comments, add client_id FK to pricing_scenarios

Revision ID: 890275f480f9
Revises: 920f77318603
Create Date: 2026-06-16 16:36:31.967950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '890275f480f9'
down_revision: Union[str, Sequence[str], None] = '920f77318603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussion_comments', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('discussion_posts', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('pricing_scenarios', sa.Column('client_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'pricing_scenarios', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Backfill: registros com deleted_at preenchido devem ter is_active = False
    op.execute("UPDATE discussion_posts SET is_active = FALSE WHERE deleted_at IS NOT NULL")
    op.execute("UPDATE discussion_comments SET is_active = FALSE WHERE deleted_at IS NOT NULL")

    # Backfill: vincular pricing_scenarios existentes ao client_id correto
    op.execute("""
        UPDATE pricing_scenarios ps
        SET client_id = c.id
        FROM clients c
        WHERE c.name = ps.client_name
          AND c.user_id = ps.user_id
          AND c.deleted_at IS NULL
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pricing_scenarios', type_='foreignkey')
    op.drop_column('pricing_scenarios', 'client_id')
    op.drop_column('discussion_posts', 'is_active')
    op.drop_column('discussion_comments', 'is_active')
    # ### end Alembic commands ###
